#!/bin/bash
# Full PBE-D3 campaign, chained: relaxations -> frozen-fragment single points ->
# convergence checks -> collection. Inputs are generated by the Windows-side Python
# (WSL interop), jobs run with pw.x in WSL. Each runner skips jobs already done,
# so the script can be relaunched after an interruption.
REPO="/mnt/c/Users/Andre/Proyectos doctorado/nano-qsar-ai-papers/mxene-glioblastoma-qsar-ai"
PY="/mnt/c/Users/Andre/AppData/Local/Programs/Python/Python312/python.exe"
cd "$REPO/calculations/gbm_dft"
log() { echo "$(date '+%F %T') $*" >> campaign.log; }
log "start"
NP=12 bash run_all.sh;                                   log "relaxations finished"
(cd "$REPO" && "$PY" src/quantum/qe_mxene_dft.py fragments) >> campaign.log 2>&1
NP=12 bash run_fragments.sh;                             log "fragments finished"
(cd "$REPO" && "$PY" src/quantum/qe_mxene_dft.py checks) >> campaign.log 2>&1
NP=12 bash run_checks.sh;                                log "checks finished"
(cd "$REPO" && "$PY" src/quantum/qe_mxene_dft.py collect && "$PY" src/quantum/qe_mxene_dft.py collect-checks \
  && "$PY" src/verification/verify_dft.py) >> campaign.log 2>&1
log "collected; campaign done"
